FORMAT: 1A
HOST: https://gentle-anchorage-46419.herokuapp.com/adapter

# Adapter service

Adapter service is a part of IntroSDE final project 2016. It calls external API
from Forismatic.com and obtains motivational quotes, that are later used by users
to motivate themselves on their way towards fitness.

## Obtaining a quotation [/getQuote]

### getQuote [GET]

+ Response 200 (application/json)

        {
          "quoteText": "Id rather regret the things that I have done than the things that I have not done. ",
          "senderLink": "",
          "senderName": "",
          "quoteLink": "http://forismatic.com/en/f775b71bf9/",
          "quoteAuthor": "Lucille Ball "
        }